// import Navigation from "../../components/Navigation";


const TermsAndConditions = () => {
  return (
    <div>
      {/* <Navigation /> */}
      <div className="main1">
        <h3>Terms & Conditions : </h3>
        <hr />
        <p align="justify">
          This document is an electronic record in terms of Information
          Technology Act, 2000 and rules thereunder, as applicable and the
          amended provisions pertaining to electronic records in various
          statutes, as amended from time to time by the Information Technology
          Act, 2000. This electronic record is generated by a computer system
          and does not require any physical or digital signatures. This document
          is published in accordance with the provisions of Rule 3(1) of the
          Information Technology (Intermediaries guidelines) Rules, 2011 that
          requires publishing of the rules and regulations, privacy policy and
          Terms of Use for access or usage of www.pharmeasy.in website and its
          mobile applications.{" "}
        </p>

        <h5>Personal Information :</h5>
        <p align="justify">
          Company shall enable You to make the requisition of Products and
          Services available to You through the Website, only if You have
          provided Company certain required User information, including without
          limitation, name; user ID; email address; address; gender; age; phone
          number; password; valid finance account information; and other details
          and created an account ("Account") through Company ID and password or
          other log-in ID and password, which can include a facebook, gmail,
          yahoo ID or any other valid email ID (collectively, the "Account
          Information"). The transaction and delivery of the Products by the
          registered merchants/vendors may also be subject to procedures for use
          of the Website, Terms, uploaded guidelines, rules, additional terms of
          service, or other disclaimer & notices, if any ("Additional Terms").
          If there is any conflict between the Terms and the Additional Terms,
          the Additional Terms shall take precedence in relation to that
          service.
        </p>
        <br />
        <h5>Services overview :</h5>
        <p align="justify">
          The Website is a platform that facilitates, as an intermediary, the
          online requisition by the user for purchase of medicines and wellness
          / health related products and services offered by Company's various
          registered third-party/ies (third-parties shall for the purpose of
          this Terms, include without limitation, third party retail pharmacies,
          third-party labs et al) ("Products and Services"). The sale & purchase
          / transaction between the registered third-parties and You, of
          Products and Services, facilitated by the requisition placed by You on
          the Website shall be governed by these Terms. Company is not and
          cannot be a party to or save as except as may be provided in these
          Terms of Use, control in any manner, any transaction between You and
          the third-parties. Company further reserves the right to change or
          modify these Terms of Use or any policy or guidelines of the Website
          including the Privacy Policy, at any time and in its sole discretion.
          Any changes or modifications made will be effective immediately upon
          posting the revisions on the Website and You waive any right You may
          have to receive specific notice of such changes or modifications.
        </p>
        <br />
        <h5>Eligibility :</h5>
        <p align="justify">
          Use of the Website is available only to persons who can form legally
          binding contracts under Indian Contract Act, 1872. Persons who are
          "incompetent to contract" within the meaning of the Indian Contract
          Act, 1872 including without limitation, minors, un-discharged
          insolvents etc. are not eligible to use the Website. The Products
          shall also not available to any Users suspended or removed from the
          company’s system for any reason whatsoever. If You do not conform to
          the above qualification, You will not be permitted to put a
          requisition for the Products through the Website. By accessing and
          using this Website, You represent that You are of legal age to form a
          binding contract and are not a person barred from receiving services
          under the laws as applicable in India. Notwithstanding the foregoing,
          if You are below the age of eighteen (18) years, You may avail the
          services provided by the Website, through Your legal guardian in
          accordance with the applicable laws.
        </p>
        <br />
        <h5> Intellectual property Rights :</h5>
        <p align="justify">
          {" "}
          The Website, the processes, and their selection and arrangement,
          including but not limited to all text, graphics, user interfaces,
          visual interfaces, sounds and music (if any), artwork and computer
          code (collectively, the "Content") on the Website is owned and
          controlled by Company and the design, structure, selection,
          coordination, expression, look and feel and arrangement of such
          Content is protected by copyright, patent and trademark laws, and
          various other intellectual property rights. The trademarks, logos and
          service marks displayed on the Website ("Marks") are the property of
          Company or their third parties or respective third parties. You are
          not permitted to use the Marks without the prior consent of Company,
          the relevant third parties that may own the Marks. Unless otherwise
          indicated or anything contained to the contrary or any proprietary
          material owned by a third party and so expressly mentioned, Company
          owns all intellectual property rights to and into the trademark
          “www.pharmeasy.in”, and the Website, including, without limitation,
          any and all rights, title and interest in and to copyright, related
          rights, patents, utility models, designs, know-how, trade secrets and
          inventions (patent pending), goodwill, source code, meta tags,
          databases, text, content, graphics, icons, and hyperlinks. Except as
          expressly provided herein, You acknowledge and agree that You shall
          not copy, republish, post, display, translate, transmit, reproduce or
          distribute any Content through any medium without obtaining the
          necessary authorization from Company or third party owner of such
          Content.
        </p>

        <h5>Return, Refund, Cancellation And Shipping Charges:</h5>
        <p align="justify">
          We offer return and refund on the products and Services ordered by You
          on the Website which are subject to further terms and conditions as
          detailed in the return, refund, cancellation and shipping charges
          policy (“Return and Refund Policy”). The Return and Refund Policy
          forms an integral part of these Terms of Use and the Users are
          requested to carefully read the same.
        </p>
        <br />
      </div>
    </div>
  );
};
export default TermsAndConditions;